/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Playfair Display', 'Georgia', 'serif'],
        body: ['DM Sans', 'system-ui', 'sans-serif'],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Noto Serif", "serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "kds-timer": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Noto Serif", "serif"],
        "noto-serif": ["Noto Serif", "serif"]
      },
      fontSize: {
        "label-sm": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "kds-timer": ["32px", {"lineHeight": "1", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      spacing: {
        "margin_desktop": "40px",
        "xl": "48px",
        "base": "4px",
        "sm": "16px",
        "gutter": "16px",
        "margin_mobile": "20px",
        "xs": "8px",
        "lg": "32px",
        "md": "24px"
      },
      colors: {
        "on-tertiary-fixed-variant": "#004d67",
        "surface-container-highest": "#e6e2dc",
        "surface-container-high": "#ebe8e2",
        "secondary-fixed-dim": "#ffb95f",
        "tertiary-container": "#489dc5",
        "surface-container-low": "#f7f3ed",
        "outline-variant": "#d7c3b3",
        "surface-bright": "#fdf9f3",
        "inverse-primary": "#ffb86e",
        "surface-dim": "#dddad4",
        "on-background": "#1c1c18",
        "on-secondary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#693c00",
        "surface": "#fdf9f3",
        "tertiary": "#006688",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#895104",
        "secondary": "#855300",
        "tertiary-fixed-dim": "#7fd0fa",
        "surface-variant": "#e6e2dc",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f4f0ea",
        "on-primary-container": "#442500",
        "on-tertiary-container": "#003143",
        "primary-fixed": "#ffdcbd",
        "on-primary-fixed": "#2c1600",
        "on-primary": "#ffffff",
        "background": "#fdf9f3",
        "on-secondary-container": "#684000",
        "outline": "#847466",
        "on-secondary-fixed": "#2a1700",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#524438",
        "surface-container": "#f1ede7",
        "error-container": "#ffdad6",
        "primary-container": "#c8853a",
        "secondary-container": "#fea619",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#c2e8ff",
        "inverse-surface": "#31302d",
        "primary-fixed-dim": "#ffb86e",
        "on-tertiary-fixed": "#001e2b",
        "primary": "#895104",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffddb8",
        "on-secondary": "#ffffff",
        amber: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        charcoal: {
          800: '#1a1a2e',
          900: '#0f0f1a',
        },
        restaurant: {
          cream: '#faf6f0',
          warm: '#f5ede0',
          amber: '#c8853a',
          deep: '#2d1a0e',
          green: '#2d6a4f',
          red: '#c0392b',
        }
      },
      animation: {
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        }
      }
    },
  },
  plugins: [],
}
